const errorCodes = {
  BAD_REQUEST_ERROR: 400,
  AUTHENTICATION_ERROR: 401,
  AUTHORIZATION_ERROR: 403,
  RESOURCE_NOT_FOUND_ERROR: 404,
  CONFLICTS_ERROR: 409,
  INTERNAL_SERVER_ERROR: 500
}

const successCodes = {
  REQUEST_SUCCESS: 200,
  RESOURCE_CREATED_SUCCESS: 201
}

module.exports = {
  errorCodes,
  successCodes
}